from class_def import NjoyCard, NjoyInput
import Data_bases 

class Groupr:
    def __init__(self):
        self.name = "groupr"
        self.description = (
            "GROUPR generates self-shielded multigroup cross-sections, group-to-group scattering matrices, "
            "and photon production matrices from pointwise ENDF and PENDF data.\n\n"
            "It averages detailed pointwise data over user-defined or standard energy bins (groups) "
            "using a neutron flux spectrum as a weighting function. It explicitly calculates self-shielding "
            "using the Bondarenko narrow-resonance approximation.\n\n"
            "The output is a GENDF tape, which is the fundamental input for many deterministic transport "
            "codes (e.g., DRAGON, PARTISN, WIMS, TRANSX).\n\n"
            "Reference: NJOY2016 Manual, Section 8, Page 77."
        )
        self.ref = "NJOY2016 Manual, Section 8, Page 77"
        self.cards = []
        self.regenerate()

    def regenerate(self):
        self.cards = []

        # ======================================================================
        # 1. HELPERS
        # ======================================================================
        def is_int(x):
            try: return int(x) or True
            except: return False
        
        def is_float(x):
            try: return float(x) or True
            except: return False

        # --- Conditionals ---
        def is_ign_arbitrary(): return int(self.c2.ign.value) == 1
        def is_igg_arbitrary(): return int(self.c2.igg.value) == 1
        def is_iwt_flux_calc(): return int(self.c2.iwt.value) < 0
        def is_iwt_tabulated(): return abs(int(self.c2.iwt.value)) == 1
        def is_iwt_analytic(): return abs(int(self.c2.iwt.value)) == 4
        def is_iwt_tape(): return int(self.c2.iwt.value) == 0
        
        # --- Card 9 Toggle ---
        def is_auto_processing():
            try: return int(self.c9_dummy.auto.value) == 1
            except: return False
            
        def is_manual_processing():
            try: return int(self.c9_dummy.auto.value) == 0
            except: return True

        # ======================================================================
        # 2. CARD DEFINITIONS
        # ======================================================================

        # --- Card 1: Units ---
        c1 = NjoyCard("c1", "Card 1: I/O Units", "Page 77")
        
        c1.add_input(NjoyInput(
            "nendf", 
            "Input ENDF Tape (NENDF).\n"
            "The logical unit number for the original ENDF/B formatted tape (File 1 & 2).\n"
            "GROUPR reads atomic masses, Q-values, and resonance parameters directly from this source.",
            20, rule=is_int, is_input_file=True, ref="Page 77"
        ))
        
        c1.add_input(NjoyInput(
            "npen", 
            "Input PENDF Tape (NPEND).\n"
            "The unit containing pointwise cross-sections previously generated by RECONR/BROADR/THERMR.\n"
            "This file must contain the detailed energy grid data to be averaged.",
            22, rule=is_int, is_input_file=True, ref="Page 77"
        ))
        
        c1.add_input(NjoyInput(
            "ngout1", 
            "Output GENDF Tape (NGOUT1).\n"
            "The unit number where the resulting multigroup library (GENDF format) will be written.\n"
            "This is the primary output used by downstream transport codes.",
            30, rule=is_int, is_output_file=True, ref="Page 77"
        ))
        
        c1.add_input(NjoyInput(
            "ngout2", 
            "Output Tape 2 (NGOUT2).\n"
            "Secondary output unit. Usually set to 0 (Standard).\n"
            "If > 0, it creates a blocked binary output for specific post-processors.",
            0, rule=is_int, ref="Page 77"
        ))
        self.add_card(c1, "c1")

        # --- Card 2: Control ---
        c2 = NjoyCard("c2", "Card 2: Processing Options", "Page 77")
        
        c2.add_input(NjoyInput(
            "matb", 
            "Material ID (MATB).\n"
            "The ENDF MAT number of the isotope/material to be processed (e.g., 9228 for U-235).\n"
            "It must match a material present on the NENDF and NPEND tapes.",
            125, rule=is_int, options=Data_bases.MAT_DB, ref="Page 77"
        ))
        
        ign_desc = (
            "Neutron Group Structure (IGN).\n"
            "Specifies the energy bin boundaries for neutrons.\n"
            "• 1 = Arbitrary (User must define structure in Card 6).\n"
            "• 2 = CSEWG (239 groups).\n"
            "• 3 = LANL (30 groups).\n"
            "• 19 = ECCO (33 groups).\n"
            "Refer to Manual Page 232 for full list."
        )
        c2.add_input(NjoyInput("ign", ign_desc, 3, rule=is_int, options=Data_bases.IGN_DB, ref="Page 232"))
        
        igg_desc = (
            "Gamma Group Structure (IGG).\n"
            "Specifies the energy bins for photon production/interaction.\n"
            "• 0 = None (No gamma processing).\n"
            "• 1 = Arbitrary (User must define structure in Card 7).\n"
            "• 2 = Constant (Single group).\n"
            "• 6 = LANL (48 groups).\n"
            "Refer to Manual Page 232 for full list."
        )
        c2.add_input(NjoyInput("igg", igg_desc, 0, rule=is_int, options=Data_bases.IGG_DB, ref="Page 232"))
        
        iwt_desc = (
            "Weight Function (IWT).\n"
            "Defines the flux spectrum used to average the pointwise cross-sections.\n"
            "• 0 = Read from tape (NINWT).\n"
            "• 3 = 1/E spectrum.\n"
            "• 4 = Standard LWR (1/E + Fission + Maxwellian).\n"
            "• < 0 = Calculate flux using Bondarenko model (Activates Card 8).\n"
            "Refer to Manual Page 233."
        )
        c2.add_input(NjoyInput("iwt", iwt_desc, 4, rule=is_int, options=Data_bases.IWT_DB, ref="Page 233"))
        
        c2.add_input(NjoyInput(
            "lord", 
            "Legendre Order (LORD).\n"
            "The maximum Legendre expansion order for scattering matrices.\n"
            "• 0 = Isotropic scattering (P0).\n"
            "• 1 = Linear anisotropy (P1).\n"
            "Typically 0-5 depending on the transport application.",
            0, rule=is_int, ref="Page 77"
        ))
        
        c2.add_input(NjoyInput(
            "ntemp", 
            "Number of Temperatures (NTEMP).\n"
            "The number of temperature sets to process.\n"
            "This value must exactly match the number of temperatures listed in Card 4.",
            1, rule=is_int, ref="Page 77"
        ))
        
        c2.add_input(NjoyInput(
            "nsigz", 
            "Number of Sigma-Zeroes (NSIGZ).\n"
            "The number of background cross-section values used for self-shielding tables.\n"
            "Must match the count in Card 5.",
            1, rule=is_int, ref="Page 77"
        ))
        
        c2.add_input(NjoyInput(
            "iprint", 
            "Print Level (IPRINT).\n"
            "Controls the verbosity of the output listing.\n"
            "• 0 = Minimum (Summary only).\n"
            "• 1 = Maximum (Prints matrices, flux moments, and detailed checks).",
            1, rule=is_int, ref="Page 77"
        ))
        
        c2.add_input(NjoyInput(
            "ismooth", 
            "Smoothing Option (ISMOOTH).\n"
            "Controls the smoothing of the calculated flux (if IWT < 0).\n"
            "• 0 = No smoothing.\n"
            "• 1 = Apply smoothing to remove resonance fluctuations.",
            0, rule=is_int, ref="Page 77"
        ))
        self.add_card(c2, "c2")

        # --- Card 3: Title ---
        c3 = NjoyCard("c3", "Card 3: Run Title", "Page 77")
        c3.add_input(NjoyInput(
            "title", 
            "Descriptive Title (TITLE).\n"
            "A descriptive string (up to 80 chars) that will be written to the GENDF file header.\n"
            "Useful for identifying the library version (e.g. 'U-235 ENDF/B-VIII.0 Fast Spectrum').",
            "'GROUPR RUN'", ref="Page 77"
        ))
        self.add_card(c3, "c3")

        # --- Card 4: Temperatures ---
        c4 = NjoyCard("c4", "Card 4: Temperatures", "Page 77")
        c4.add_input(NjoyInput(
            "temp", 
            "List of Temperatures (TEMP).\n"
            "A space-separated list of temperatures (in Kelvin) to process.\n"
            "These temperatures must exist on the input PENDF tape.\n"
            "Example: '293.6 600.0 900.0'.",
            "293.6", ref="Page 77"
        ))
        self.add_card(c4, "c4")

        # --- Card 5: Sigma Zero ---
        c5 = NjoyCard("c5", "Card 5: Sigma Zero Values", "Page 77")
        c5.add_input(NjoyInput(
            "sigz", 
            "Sigma Zero Values (SIGZ).\n"
            "A list of background cross-sections (in barns) for Bondarenko self-shielding.\n"
            "• Large value (1.0e10) = Infinite Dilution (No shielding).\n"
            "• Small values (10, 100) = Heavily shielded.\n"
            "Standard set: '1.0e10 10000 1000 100 10 1'.",
            "1.0e10", ref="Page 77"
        ))
        self.add_card(c5, "c5")

        # ======================================================================
        # CONDITIONAL CARDS (6, 7, 8)
        # ======================================================================

        # --- Card 6: User Neutron Groups ---
        c6 = NjoyCard("c6_groups", "Card 6a/b: User Neutron Groups", "Page 77", active_if=is_ign_arbitrary)
        c6.add_input(NjoyInput("ngn", "Number of Neutron Groups (NGN).\nThe total number of energy bins.", 0, rule=is_int, ref="Page 77"))
        c6.add_input(NjoyInput("egn", "Group Boundaries (EGN).\nA list of NGN+1 energy values (eV) defining the group boundaries, from low energy to high energy.", "1.0e-5 20.0e6", ref="Page 77"))
        self.add_card(c6, "c6_groups")

        # --- Card 7: User Gamma Groups ---
        c7 = NjoyCard("c7_groups", "Card 7a/b: User Gamma Groups", "Page 77", active_if=is_igg_arbitrary)
        c7.add_input(NjoyInput("ngg", "Number of Gamma Groups (NGG).\nThe total number of photon energy bins.", 0, rule=is_int, ref="Page 77"))
        c7.add_input(NjoyInput("egg", "Group Boundaries (EGG).\nA list of NGG+1 energy values (eV) defining the photon group boundaries.", "1.0e-5 20.0e6", ref="Page 77"))
        self.add_card(c7, "c7_groups")

        # --- Card 8a: Flux Calculator Parameters ---
        c8a_desc = "Card 8a: Flux Calculator Parameters. Active when IWT < 0. Computes a material-specific flux."
        c8a = NjoyCard("c8a_flux", c8a_desc, "Page 78", active_if=is_iwt_flux_calc)
        
        c8a.add_input(NjoyInput("fehi", "Flux Break Energy (FEHI).\nThe energy (eV) above which the Bondarenko smooth flux model is used instead of the calculated flux.", "1.0e3", rule=is_float, ref="Page 232"))
        c8a.add_input(NjoyInput("sigpot", "Potential Scattering XS (SIGPOT).\nEstimate of the potential scattering cross-section (barns per absorber atom). Used for resonance self-shielding.", 10.0, rule=is_float, ref="Page 232"))
        c8a.add_input(NjoyInput("nflmax", "Max Flux Points (NFLMAX).\nThe maximum number of energy points to use in the flux calculation (typically 100-1000).", 100, rule=is_int, ref="Page 232"))
        c8a.add_input(NjoyInput("ninwt", "Flux Output Tape (NINWT).\nIf set (>0), the calculated flux is saved to this binary tape unit.", 0, rule=is_int, ref="Page 232"))
        c8a.add_input(NjoyInput("jsigz", "Ref Sigma-Zero Index (JSIGZ).\nThe index of the sigma-zero value in the SIGZ array to use as the reference for the flux calculation (Default=0/1).", 1, rule=is_int, ref="Page 232"))
        c8a.add_input(NjoyInput("alpha2", "Admix Alpha (ALPHA2).\nAlpha parameter (4A/(A+1)^2) for an admixed moderator (0.0 = None).", 0.0, rule=is_float, ref="Page 232"))
        c8a.add_input(NjoyInput("sam", "Admix XS (SAM).\nThe macroscopic cross-section of the admixed moderator in barns per absorber atom.", 0.0, rule=is_float, ref="Page 232"))
        c8a.add_input(NjoyInput("beta", "Heterogeneity (BETA).\nHeterogeneity parameter for equivalence theory (0.0 = Homogeneous).", 0.0, rule=is_float, ref="Page 232"))
        c8a.add_input(NjoyInput("alpha3", "Ext Moderator Alpha (ALPHA3).\nAlpha parameter for an external moderator (e.g. clad/coolant).", 0.0, rule=is_float, ref="Page 232"))
        c8a.add_input(NjoyInput("gamma", "Admix Fraction (GAMMA).\nThe fraction of admixed moderator cross-section effectively appearing in the external moderator.", 0.0, rule=is_float, ref="Page 232"))
        self.add_card(c8a, "c8a_flux")

        # --- Card 8b: Tabulated Weight ---
        c8b = NjoyCard("c8b_tab", "Card 8b: Tabulated Weight Function", "Page 78", active_if=is_iwt_tabulated)
        c8b.add_input(NjoyInput("wght", "Weight Function (WGHT).\nA TAB1 formatted record defining the flux (Energy vs Value). Must end with a slash (/).\nExample: 1.0e-5 1.0 2.0e7 1.0 / (Constant).", "0.0 0.0 /", ref="Page 232"))
        self.add_card(c8b, "c8b_tab")

        # --- Card 8c: Analytic Weight ---
        c8c = NjoyCard("c8c_ana", "Card 8c: Analytic Weight Parameters", "Page 78", active_if=is_iwt_analytic)
        
        c8c.add_input(NjoyInput("eb", "Thermal Break (EB).\nThe energy (eV) boundary between the Thermal Maxwellian and the 1/E region.", 0.0253, rule=is_float, ref="Page 232"))
        c8c.add_input(NjoyInput("tb", "Thermal Temperature (TB).\nThe temperature (eV) of the Thermal Maxwellian spectrum.", 0.0253, rule=is_float, ref="Page 232"))
        
        # UPDATED: Use scientific string format for large numbers
        c8c.add_input(NjoyInput("ec", "Fission Break (EC).\nThe energy (eV) boundary between the 1/E region and the Fission Spectrum.", "8.2e5", rule=is_float, ref="Page 232"))
        c8c.add_input(NjoyInput("tc", "Fission Temperature (TC).\nThe temperature (eV) of the Fission Spectrum.", "1.27e6", rule=is_float, ref="Page 232"))
        self.add_card(c8c, "c8c_ana")

        # --- Card 8d: Input Flux Tape ---
        c8d = NjoyCard("c8d_tape", "Card 8d: Input Flux Tape", "Page 78", active_if=is_iwt_tape)
        c8d.add_input(NjoyInput("ninwt", "Input Flux Tape (NINWT).\nThe binary unit number containing the pre-calculated weighting flux.", 0, rule=is_int, ref="Page 233"))
        self.add_card(c8d, "c8d_tape")

        # ======================================================================
        # 3. REACTION LOOP (Card 9)
        # ======================================================================
        
        c9_desc = "Card 9: Reaction List. Defines which reactions to process from the ENDF/PENDF tapes."
        c9_dummy = NjoyCard("c9", c9_desc, "Page 78")
        
        auto_opts = {1: "Automatic (Process All Reactions in File)", 0: "Manual (Select Specific MT)"}
        c9_dummy.add_input(NjoyInput("auto", "Processing Mode", 1, rule=is_int, options=auto_opts, hidden_in_file=True))
        self.add_card(c9_dummy, "c9_dummy")
        
        # --- Card 9a: Auto (Visible if auto=1) ---
        c9a = NjoyCard("c9a_auto", "Card 9: Automatic Selection", "Page 233", active_if=is_auto_processing)
        mfd_auto_desc = (
            "Automatic Macro (MFD).\n"
            "Selects a predefined set of reactions to process automatically.\n"
            "• 3 = Process all Cross Sections (File 3).\n"
            "• 6 = Process all Matrices (File 4/5/6).\n"
            "• 12 = Process all Photon Production (Yields).\n"
            "This writes 'MFD /' to the input file."
        )
        c9a.add_input(NjoyInput("mfd", mfd_auto_desc, 3, rule=is_int, options=Data_bases.MFD_AUTO_DB, ref="Page 233"))
        self.add_card(c9a, "c9a_auto")
        
        # --- Card 9b: Manual (Visible if auto=0) ---
        c9b = NjoyCard("c9b_manual", "Card 9: Manual Selection", "Page 233", active_if=is_manual_processing)
        
        mfd_manual_desc = (
            "File Number (MFD).\n"
            "The ENDF File Number containing the data to process.\n"
            "• 3 = Reaction Cross Sections.\n"
            "• 6 = Energy-Angle Matrices.\n"
            "• 12 = Photon Production Yields."
        )
        c9b.add_input(NjoyInput("mfd", mfd_manual_desc, 3, rule=is_int, options=Data_bases.MFD_MANUAL_DB, ref="Page 233"))
        
        mtd_desc = (
            "Reaction MT (MTD).\n"
            "The specific reaction identifier to process.\n"
            "• 102 = Capture (n,g).\n"
            "• 18 = Fission.\n"
            "• 221/222 = Thermal Scattering.\n"
            "Set to 0 to terminate the reaction list."
        )
        c9b.add_input(NjoyInput("mtd", mtd_desc, 102, rule=is_int, options=Data_bases.MTD_DB, ref="Page 233"))
        
        c9b.add_input(NjoyInput("mtname", "Description (MTNAME).\nA short description string for the reaction (e.g. 'Radiative Capture').", "'Reaction Description'", ref="Page 233"))
        self.add_card(c9b, "c9b_manual")

        # --- Card 10: Termination ---
        c10_desc = "Card 10: Run Termination. Signals the end of the GROUPR run for this material."
        c10 = NjoyCard("c10", c10_desc, "Page 78")
        c10.add_input(NjoyInput("matd", "Next Material (MATD).\nMust be 0 to terminate the run properly.", 0, rule=is_int, ref="Page 234"))
        self.add_card(c10, "c10")

    def add_card(self, card, name=None):
        self.cards.append(card)
        if name: setattr(self, name, card)

    def write(self):
        lines = [self.name]
        
        c1 = self.c1
        lines.append(f"{c1.nendf.value} {c1.npen.value} {c1.ngout1.value} {c1.ngout2.value}/")
        
        c2 = self.c2
        lines.append(f"{c2.matb.value} {c2.ign.value} {c2.igg.value} {c2.iwt.value} "
                     f"{c2.lord.value} {c2.ntemp.value} {c2.nsigz.value} "
                     f"{c2.iprint.value} {c2.ismooth.value}/")
        
        title_val = str(self.c3.title.value).strip("'\"")
        lines.append(f"'{title_val}'/")
        lines.append(f"{str(self.c4.temp.value).replace(',', ' ')}/")
        lines.append(f"{str(self.c5.sigz.value).replace(',', ' ')}/")
        
        # --- Conditional Cards ---
        if int(c2.ign.value) == 1:
            lines.append(f"{self.c6_groups.ngn.value}/")
            lines.append(f"{self.c6_groups.egn.value}/")
            
        if int(c2.igg.value) == 1:
            lines.append(f"{self.c7_groups.ngg.value}/")
            lines.append(f"{self.c7_groups.egg.value}/")
            
        iwt = int(c2.iwt.value)
        if iwt < 0:
            c = self.c8a_flux
            lines.append(f"{c.fehi.value} {c.sigpot.value} {c.nflmax.value} {c.ninwt.value} {c.jsigz.value} "
                         f"{c.alpha2.value} {c.sam.value} {c.beta.value} {c.alpha3.value} {c.gamma.value}/")
        if abs(iwt) == 1:
            lines.append(f"{self.c8b_tab.wght.value}/")
        if abs(iwt) == 4:
            c = self.c8c_ana
            lines.append(f"{c.eb.value} {c.tb.value} {c.ec.value} {c.tc.value}/")
        if iwt == 0:
            lines.append(f"{self.c8d_tape.ninwt.value}/")
            
        # --- Card 9: Auto/Manual ---
        is_auto = False
        try: is_auto = (int(self.c9_dummy.auto.value) == 1)
        except: pass
        
        if is_auto:
            mfd = self.c9a_auto.mfd.value
            lines.append(f"{mfd}/")
            lines.append("0/") 
        else:
            mfd = self.c9b_manual.mfd.value
            mtd = self.c9b_manual.mtd.value
            name = str(self.c9b_manual.mtname.value).strip("'\"")
            if str(mtd) == "0":
                lines.append(f"{mfd} 0 '/")
            else:
                lines.append(f"{mfd} {mtd} '{name}'/")
                lines.append("0/")
        
        # --- Card 10: Fixed 0 ---
        lines.append("0/") 
        
        return "\n".join(lines)

    @property
    def input_files(self): return [self.c1.nendf.value, self.c1.npen.value]
    @property
    def output_files(self): return [self.c1.ngout1.value]