import tkinter as tk
from tkinter import ttk, filedialog, simpledialog, messagebox
import os

class TapeLibraryPanel(ttk.LabelFrame):
    def __init__(self, parent_widget, controller):
        super().__init__(parent_widget, text="2. Tape Library", padding=5)
        self.controller = controller
        self._setup_ui()

    def _setup_ui(self):
        # --- Toolbar ---
        lib_tool = ttk.Frame(self)
        lib_tool.pack(fill="x", pady=(0, 5))
        ttk.Button(lib_tool, text="+ Load Input File", command=self.add_input_tape).pack(side="left")

        # --- Split Columns Container ---
        lib_split = ttk.Frame(self)
        lib_split.pack(fill="both", expand=True)
        
        # Configure the split container to distribute width equally
        lib_split.columnconfigure(0, weight=1)
        lib_split.columnconfigure(1, weight=1)
        lib_split.rowconfigure(0, weight=1) # Ensure columns expand vertically

        # ==========================
        # COLUMN 1: USER INPUTS
        # ==========================
        col1 = ttk.Frame(lib_split)
        col1.grid(row=0, column=0, sticky="nsew", padx=(0,5))
        
        # USE GRID LAYOUT: Row 0=Header, Row 1=List (Expands), Row 2=Buttons (Fixed)
        col1.columnconfigure(0, weight=1)
        col1.rowconfigure(1, weight=1) # This row absorbs resizing

        # Row 0: Header
        tk.Label(col1, text="User Inputs ", fg="green", font=("Segoe UI", 9, "bold"), bg="white").grid(row=0, column=0, sticky="w")
        
        # Row 1: Treeview & Scrollbar
        self.tree_user = ttk.Treeview(col1, columns=("Unit", "File"), show='headings', height=4) # Height is default lines
        self.tree_user.heading("Unit", text="Unit")
        self.tree_user.heading("File", text="File Name")
        self.tree_user.column("Unit", width=40, anchor="center")
        self.tree_user.grid(row=1, column=0, sticky="nsew", pady=2)
        
        sb_user = ttk.Scrollbar(col1, orient="vertical", command=self.tree_user.yview)
        sb_user.grid(row=1, column=1, sticky="ns")
        self.tree_user.configure(yscrollcommand=sb_user.set)

        # Row 2: Buttons (Always visible)
        btn_frame1 = ttk.Frame(col1)
        btn_frame1.grid(row=2, column=0, columnspan=2, sticky="ew", pady=2)
        ttk.Button(btn_frame1, text="Change Unit", command=self.change_tape_unit).pack(side="left", fill="x", expand=True, padx=(0,1))
        ttk.Button(btn_frame1, text="Remove", command=self.remove_input_tape).pack(side="left", fill="x", expand=True, padx=(1,0))

        # ==========================
        # COLUMN 2: MODULE OUTPUTS
        # ==========================
        col2 = ttk.Frame(lib_split)
        col2.grid(row=0, column=1, sticky="nsew")
        
        col2.columnconfigure(0, weight=1)
        col2.rowconfigure(1, weight=1)

        # Row 0: Header
        tk.Label(col2, text="Module Outputs", fg="blue", font=("Segoe UI", 9, "bold"), bg="white").grid(row=0, column=0, sticky="w")
        
        # Row 1: Treeview & Scrollbar
        self.tree_mods = ttk.Treeview(col2, columns=("Unit", "Desc"), show='headings', height=4)
        self.tree_mods.heading("Unit", text="Unit")
        self.tree_mods.heading("Desc", text="Generated By")
        self.tree_mods.column("Unit", width=40, anchor="center")
        self.tree_mods.grid(row=1, column=0, sticky="nsew", pady=2)

        sb_mods = ttk.Scrollbar(col2, orient="vertical", command=self.tree_mods.yview)
        sb_mods.grid(row=1, column=1, sticky="ns")
        self.tree_mods.configure(yscrollcommand=sb_mods.set)

        # Row 2: Spacer/Placeholder (to align visuals with col1)
        # We add an empty frame just to keep bottom alignment consistent if needed
        ttk.Frame(col2, height=28).grid(row=2, column=0, pady=2)

    def refresh(self):
        for item in self.tree_user.get_children(): self.tree_user.delete(item)
        for item in self.tree_mods.get_children(): self.tree_mods.delete(item)

        for unit, path in sorted(self.controller.user_tapes.items()):
            self.tree_user.insert("", "end", values=(unit, os.path.basename(path)))

        for unit, desc in sorted(self.controller.module_tapes.items()):
            self.tree_mods.insert("", "end", values=(unit, desc))

    def add_input_tape(self):
        f = filedialog.askopenfilename(title="Select Input ENDF/PENDF Tape")
        if not f: return
        default_unit = 20
        while default_unit in self.controller.user_tapes: default_unit += 1
        unit = simpledialog.askinteger("Assign Unit", f"Assign NJOY Unit Number for:\n{os.path.basename(f)}", initialvalue=default_unit, minvalue=20, maxvalue=99)
        if unit:
            if unit in self.controller.user_tapes:
                if not messagebox.askyesno("Overwrite", f"Unit {unit} exists. Overwrite?"): return
            self.controller.user_tapes[unit] = f
            self.refresh()

    def remove_input_tape(self):
        selected = self.tree_user.selection()
        if not selected: 
            messagebox.showinfo("Select Item", "Please select a tape from the list first.")
            return
        item_vals = self.tree_user.item(selected[0], "values")
        unit = int(item_vals[0])
        if messagebox.askyesno("Confirm Remove", f"Remove Tape {unit} from library?"):
            if unit in self.controller.user_tapes:
                del self.controller.user_tapes[unit]
                self.refresh()

    def change_tape_unit(self):
        selected = self.tree_user.selection()
        if not selected: 
            messagebox.showinfo("Select Item", "Please select a tape from the list first.")
            return
        item_vals = self.tree_user.item(selected[0], "values")
        old_unit = int(item_vals[0])
        path = self.controller.user_tapes[old_unit]
        new_unit = simpledialog.askinteger("Change Unit", f"Enter new unit number for:\n{os.path.basename(path)}", initialvalue=old_unit, minvalue=20, maxvalue=99)
        if new_unit and new_unit != old_unit:
            if new_unit in self.controller.user_tapes:
                if not messagebox.askyesno("Overwrite", f"Unit {new_unit} is already in use. Overwrite?"): return
            del self.controller.user_tapes[old_unit]
            self.controller.user_tapes[new_unit] = path
            self.refresh()